# Generated by Django 4.1.3 on 2022-11-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='imagen')),
                ('description', models.TextField(null=True, verbose_name='descripcion')),
            ],
        ),
    ]
